baseURL = "https://example.com"
languageCode = "en"
title = "Alvin McGeeâ€™s Webpage"
theme = "hugo-theme-monochrome"
defaultContentLanguage = "en"
enableEmoji = true
paginate = 5
enableGitInfo = true

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[outputs]
home = ["HTML", "RSS", "JSON"]
